name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: node16 # Specify Node.js version 16

      - name: Autograding
        uses: education/autograding@v1
        with:
          ref: node16 # Specify Node.js version 16
